--- #YAML:1.0
name:               Regexp-MinLength
version:            0.02
abstract:           Perl extension for determining the minimum matching length for a regular expression
author:
    - Leigh  Metcalf <leigh@fprime.net>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:  {}
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
